### ISSUE TITLE
Allow custom docker arguments to expose

### ISSUE THREAD

**Issue by crisward** [dokku/dokku-redis#119] opened 2018-04-30 15:57 UTC
Not sure if this is the best place to raise this, as it applies to all the plugins with expose.

I'd quite like it if the expose command had an option to bind to 127.0.0.1 instead of 0.0.0.0. That way I could expose it to the local machine, and still access it via an ssh tunnel. This is easy to setup in many mysql/mariadb clients, but has the benefit of being more secure.

perhaps
```
dokku mariadb:expose APP --ip=127.0.0.1
```

Thoughts?

**Comment by josegonzalez** [comment] 2020-03-10 15:16
Duplicate of #86

**Closed by josegonzalez** 2020-03-10 15:16 UTC
Labels: type: enhancement, type: service

**Comment by josegonzalez** [comment] 2021-09-12 11:40
You can specify the ip to bind on when running expose:

```shell
dokku redis:expose $SERVICE 127.0.0.1:6379
```

No need for anything new. This is now also documented in the readme.
