### ISSUE TITLE
add docker-options command to limit memory consumption

### ISSUE THREAD

**Issue by jlcastillo** [dokku/dokku-redis#115] opened 2018-11-06 18:10 UTC
We can limit resources for apps using the docker-options command, but the same cannot be done for services like MySQL. As a result, MySQL takes too much memory. A simple WordPress database starts consuming 60 MB, and scales to 350 MB after 24h. For small projects with few visitors that's unreasonable.

**Comment by josegonzalez** [comment] 2019-07-17 21:14
Duplicate of #86.

**Closed by josegonzalez** 2019-07-17 21:14 UTC
Labels: type: enhancement
